### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#15]
User Story

Value Proposition

As a user,
I want to use an easily readable and accessible app regardless of my device and browser settings,
so that I have an optimal user experience.

Description

Design and implement consistent size units across all components. Optimize media screen settings for better responsiveness, readability and accessibility.

Acceptance Criteria
 
- [x] The website is easily readable on all devices (mobile, tablet, desktop).
- [x] All elements adapt to the screen size of the device.
- [x] Navigation and interaction are intuitive and consistent across different screen sizes.
- [x] Text and controls are accessible and easy to use, even for users with disabilities (e.g., screen readers, color contrast).
- [x] The site loads quickly and efficiently across various devices and network conditions.

Tasks

 - [x] Audit current size units across all components.
- [x] units are standardized as follows:
    - [x] text: rem
    - [x] margin and padding: usually px (sometimes vh/vw)
    - [x] button-width: rem
 - [x]  Implement media queries for screen size optimization (600 / 900 / 1200 px)
 - [x] Ensure accessibility across various devices and screen sizes.

**Comment by JessicaLoers** [comment]
**Hey Team** ✨

This user story contains many important elements, but there is room for improvement, particularly in distinguishing between a Developer Story and a true User Story.

A User Story should focus on the value to the user. In this case, the story is written from the perspective of a web developer, which makes it more of a Developer Story. It seems like things got a bit mixed up here.

_I would suggest transforming this into a User Story:_

**As a user**,
**I want to** to use a easily readable and accessible app regardless of my device,
**so that I** have an optimal user experience.

_The **acceptance criteria** for a User Story should be written from the user’s perspective, for example:_

- The website is easily readable on all devices (mobile, tablet, desktop).
- All elements are consistently styled and adapt to the screen size of the device.
- Navigation and interaction are intuitive and consistent across different screen sizes.
- Text and controls are accessible and easy to use, even for users with disabilities (e.g., screen readers, color contrast).
- The site loads quickly and efficiently across various devices and network conditions.


Please discuss these suggestions within the team and adapt the user story accordingly, ensuring the focus stays on delivering value to the user or developer. ✌️

**Comment by Inelukas** [comment]
Thanks for your feedback! 😊 We have updated the story.

By the way, are there any standard sizes we should use for our media queries or can we decide them ourselves?

**Comment by JessicaLoers** [comment]
If I were being really strict, I would say that the following acceptance criteria are not written from the user's perspective. However, I'm not being that strict 😁

> The Garden page becomes the new home page ("/"), and the list view becomes a sub-page ("/list").
